### ISSUE TITLE
Correctly handle unlimited number of steps

### ISSUE THREAD

**Issue by fatho** [fatho/bachelor-thesis#2]
Currently, the generation of values of ADTs with Data instance gets stuck when the first constructor is recursive.

**Solution:** Reorder constructors on the fly such that non-recursive constructors are processed first. If all constructors are recursive, inject bottom value at each recursion level.

**Comment by jvoigtlaender** [comment]
I don't think constructors should be reordered away from the order in which the user put them into the ADT definition.

Also, the bottom value should be injected at every recursion level, regardless of whether there are non-recursive constructors.

So, if the program contains

``` haskell
data Tree = Node Tree Tree | Leaf
```

then the interpretation should be:

```
generate = {_|_} `union` { Node t s | t,s from recursive generate-call} `union` {Leaf}
```

That way, you will get partial results. You won't get any total trees, but that's the programmer's fault. Their using

``` haskell
data Tree = Node Tree Tree | Leaf
```

instead of

``` haskell
data Tree = Leaf | Node Tree Tree
```

is just as "wrong" as writing a function like so:

```
f x = (f non-productive-recursive-call)  `union` base-case
```

instead of:

```
f x = base-case `union` (f non-productive-recursive-call)
```

and still expecting good results with depth-first search.

Just as the effect of preferring one of the two `f` versions over the other, the effect of choosing between the two ways to define `Tree` should be visible to the programmer, not hidden away by the compiler reordering stuff.

And concerning the "adding the bottom only when all constructors are recursive": that's an optimization in the case of breadth-first search. In the case of depth-first search, it may or may not be an optimization, depending on the recursion structure. But I don't think it is worth doing this ad-hoc optimization here in either case. Better always put the bottom in, as first choice, and rely on the general "majorisation and de-duplication" optimization that can be applied during evaluation anyway.

@mehner, what do you think?

**Comment by mehner** [comment]
I agree with Janis.
(Though, the user should get a fair chance to know about these issues.)
